# Generated by Django 2.2.7 on 2019-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('dependants', models.IntegerField()),
                ('applicantincome', models.IntegerField()),
                ('coapplicantincome', models.IntegerField()),
                ('loanamount', models.IntegerField()),
                ('loanterm', models.IntegerField()),
                ('credithistory', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('graduatededucation', models.CharField(choices=[('Graduate', 'Graduate'), ('Not_Graduate', 'Not_Graduate')], max_length=15)),
                ('selfemployed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('area', models.CharField(choices=[('Rural', 'Rural'), ('SemiUrban', 'SemiUrban'), ('Urban', 'Urban')], max_length=15)),
            ],
        ),
    ]
